/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author faira
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import librarymanagementsystem.DBConnection;
import net.proteanit.sql.DbUtils;


public class MemberForm extends javax.swing.JFrame {
    Connection conn = DBConnection.connect();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MemberForm.class.getName());

    public MemberForm() {
        initComponents();
        autoIDMember();
        loadTable();
    }
    private void loadTable() {
        try {
            String sql = "SELECT Member_ID, Member_Name, Member_Type_ID, Identifier, Email, Phone, Register_Date FROM Member";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblMember.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void autoIDMember() {
    try {
        String sql = "SELECT MAX(Member_ID) FROM member";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            String maxID = rs.getString(1);
            if (maxID == null) {
                txtMemberID.setText("M001");
            } else {
                int id = Integer.parseInt(maxID.substring(1)) + 1;
                txtMemberID.setText(String.format("M%03d", id));
            }
        }
        txtMemberID.setEditable(false);
        
    } catch (Exception e) {
        System.out.println("Error AutoID Member: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        txtMemberName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cbMemberType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        cbIdentifier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Email");

        jLabel4.setText("Type");

        jLabel5.setText("Identifier");

        jLabel6.setText("Phone");

        txtMemberID.addActionListener(this::txtMemberIDActionPerformed);

        txtMemberName.addActionListener(this::txtMemberNameActionPerformed);

        cbMemberType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GST001", "GST002", "GST003", "GST004", "GST005", "LEC001", "LEC002", "LEC003", "LEC004", "LEC005", "STD001", "STD002", "STD003", "STD004", "STD005", " " }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MEMBER FORM");

        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMember);

        cbIdentifier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff", "Guest", "Lecture", "Other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMemberID)
                                    .addComponent(txtMemberName)
                                    .addComponent(txtEmail)
                                    .addComponent(txtPhone)
                                    .addComponent(cbMemberType, 0, 200, Short.MAX_VALUE)
                                    .addComponent(cbIdentifier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Cek dulu apakah ID sudah terisi (apakah ada data yang dipilih)
        if(txtMemberID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Silakan klik data di tabel terlebih dahulu untuk dihapus!");
            return; // Menghentikan proses jika kosong
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data member ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM Member WHERE Member_ID=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, txtMemberID.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Member berhasil dihapus!");
                loadTable(); 

                txtMemberID.setText("");
                txtMemberName.setText("");
                txtEmail.setText("");
                txtPhone.setText("");
                cbIdentifier.setSelectedIndex(0);
                cbMemberType.setSelectedIndex(0);
        
             } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Delete: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        autoIDMember();
        txtMemberID.setText("");
        txtMemberName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        cbIdentifier.setSelectedIndex(0);

        cbMemberType.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtMemberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String sql = "INSERT INTO Member (Member_ID, Member_Name, Member_Type_ID, Identifier, Email, Phone) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtMemberID.getText());
            pst.setString(2, txtMemberName.getText());

            String typeValue = cbMemberType.getSelectedItem().toString();
            String typeID = typeValue.split("-")[0]; 
            pst.setString(3, typeID);

            pst.setString(4, cbIdentifier.getSelectedItem().toString());
            pst.setString(5, txtEmail.getText());
            pst.setString(6, txtPhone.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Member berhasil didaftarkan!");
            autoIDMember();
            loadTable();

            txtMemberID.setText("");
            txtMemberName.setText("");
            cbIdentifier.setSelectedIndex(0);
            txtEmail.setText("");
            txtPhone.setText("");  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberMouseClicked
        try {
            int baris = tblMember.getSelectedRow();
    
            txtMemberID.setText(tblMember.getValueAt(baris, 0).toString());
            txtMemberName.setText(tblMember.getValueAt(baris, 1).toString());
    
            String typeID = tblMember.getValueAt(baris, 2).toString();
    for (int i = 0; i < cbMemberType.getItemCount(); i++) {
        if (cbMemberType.getItemAt(i).toString().startsWith(typeID)) {
            cbMemberType.setSelectedIndex(i);
            break;
        }
    }
    
            String identifierVal = tblMember.getValueAt(baris, 3) != null ? tblMember.getValueAt(baris, 3).toString() : "Student";

            cbIdentifier.setSelectedItem(identifierVal);
            txtEmail.setText(tblMember.getValueAt(baris, 4) != null ? tblMember.getValueAt(baris, 4).toString() : "");
            txtPhone.setText(tblMember.getValueAt(baris, 5) != null ? tblMember.getValueAt(baris, 5).toString() : "");
    
        } catch (Exception e) {
            System.out.println("Error klik tabel: " + e.getMessage());
        }
    }//GEN-LAST:event_tblMemberMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String sql = "UPDATE Member SET Member_Name=?, Member_Type_ID=?, Email=?, Phone=?, Identifier=? WHERE Member_ID=?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtMemberName.getText());

            String typeValue = cbMemberType.getSelectedItem().toString();
            String typeID = typeValue.split("-")[0]; 
            pst.setString(2, typeID);

            pst.setString(3, txtEmail.getText());
            pst.setString(4, txtPhone.getText());
            pst.setString(5, cbIdentifier.getSelectedItem().toString());

            pst.setString(6, txtMemberID.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Member berhasil diubah!");

            loadTable(); 

            txtMemberID.setText("");
            txtMemberName.setText("");
            txtEmail.setText("");
            txtPhone.setText("");
            cbIdentifier.setSelectedIndex(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error Update: " + e.getMessage());
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        try {
            int baris = tblMember.getSelectedRow();
    
            txtMemberID.setText(tblMember.getValueAt(baris, 0).toString());
            txtMemberName.setText(tblMember.getValueAt(baris, 1).toString());
    
            String typeID = tblMember.getValueAt(baris, 2).toString();
        for (int i = 0; i < cbMemberType.getItemCount(); i++) {
            if (cbMemberType.getItemAt(i).toString().startsWith(typeID)) {
            cbMemberType.setSelectedIndex(i);
            break;
            }
        }
    
        String identifierVal = tblMember.getValueAt(baris, 3) != null ? tblMember.getValueAt(baris, 3).toString() : "Student";

        cbIdentifier.setSelectedItem(identifierVal);
        txtEmail.setText(tblMember.getValueAt(baris, 4) != null ? tblMember.getValueAt(baris, 4).toString() : "");
        txtPhone.setText(tblMember.getValueAt(baris, 5) != null ? tblMember.getValueAt(baris, 5).toString() : "");
    
        } catch (Exception e) {
            System.out.println("Error klik tabel: " + e.getMessage());
        }
    }//GEN-LAST:event_jScrollPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MemberForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbIdentifier;
    private javax.swing.JComboBox<String> cbMemberType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMember;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtMemberName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
