/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.oovp2026;
import java.text.SimpleDateFormat;
import java.util.Calendar;
public class Page_Journal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Page_Journal.class.getName());

    /**
     * Creates new form Page_Book
     */
    public Page_Journal() {
        initComponents();
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat calFormat = new SimpleDateFormat("dd/MM/yyyy");
        Borrow_Date.setText(calFormat.format(cal.getTime()));
    }
    
    private void countDate() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();

            // Get the date from jTextField1
            cal.setTime(sdf.parse(Borrow_Date.getText()));

            // Logic duration from Borrow_Member (JComboBox)
            String selectedMember = Borrow_Member.getSelectedItem().toString();
            int duration = 7; // Default
            
            if (selectedMember.contains("Lect") || selectedMember.contains("Std") || selectedMember.contains("Gst")) {
                duration = 14;
            }

            cal.add(Calendar.DAY_OF_MONTH, duration);

            String returnDate = sdf.format(cal.getTime());
            label17.setText("Return Date: " + returnDate);

        } catch (Exception e) {
            System.err.println("Error while counting days: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutButton = new java.awt.Button();
        MenuButton = new java.awt.Button();
        TabMenu = new javax.swing.JTabbedPane();
        Journal = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        Journal_Title = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        Journal_Institute = new javax.swing.JComboBox<>();
        label3 = new java.awt.Label();
        Journal_Author = new javax.swing.JComboBox<>();
        label4 = new java.awt.Label();
        Journal_Publisher = new javax.swing.JComboBox<>();
        label5 = new java.awt.Label();
        Journal_Year = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        Journal_City = new javax.swing.JTextField();
        label7 = new java.awt.Label();
        Journal_Index = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Journal_Table = new javax.swing.JTable();
        Add_Journal = new javax.swing.JButton();
        Edit_Journal = new javax.swing.JButton();
        Refresh_Journal = new javax.swing.JButton();
        Delete_Journal = new javax.swing.JButton();
        Institute = new javax.swing.JPanel();
        label8 = new java.awt.Label();
        Institute_Name = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        Institute_Contact = new javax.swing.JTextField();
        label18 = new java.awt.Label();
        Institute_City = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Institute_Table = new javax.swing.JTable();
        Add_Institute = new javax.swing.JButton();
        Edit_Institute = new javax.swing.JButton();
        Refresh_Institute = new javax.swing.JButton();
        Delete_Institute = new javax.swing.JButton();
        Author = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        Auth_Name = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        Auth_Contact = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Auth_Table = new javax.swing.JTable();
        Add_Auth = new javax.swing.JButton();
        Edit_Auth = new javax.swing.JButton();
        Refresh_Auth = new javax.swing.JButton();
        Delete_Auth = new javax.swing.JButton();
        Publisher = new javax.swing.JPanel();
        label12 = new java.awt.Label();
        Pub_Name = new javax.swing.JTextField();
        label13 = new java.awt.Label();
        Pub_Contact = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Pub_Table = new javax.swing.JTable();
        Add_Pub = new javax.swing.JButton();
        Edit_Pub = new javax.swing.JButton();
        Refresh_Pub = new javax.swing.JButton();
        Delete_Pub = new javax.swing.JButton();
        Borrow = new javax.swing.JPanel();
        label14 = new java.awt.Label();
        Borrow_Journal = new javax.swing.JComboBox<>();
        label15 = new java.awt.Label();
        Borrow_Member = new javax.swing.JComboBox<>();
        label16 = new java.awt.Label();
        Borrow_Date = new javax.swing.JTextField();
        label17 = new java.awt.Label();
        Return_Date = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        Borrow_Table = new javax.swing.JTable();
        Add_Borrow = new javax.swing.JButton();
        Edit_Borrow = new javax.swing.JButton();
        Refresh_Borrow = new javax.swing.JButton();
        Delete_Borrow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogOutButton.setLabel("Log Out");

        MenuButton.setLabel("Back to Menu");

        TabMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label1.setText("Title");

        Journal_Title.addActionListener(this::Journal_TitleActionPerformed);

        label2.setText("Institute");

        Journal_Institute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- uni1", "2- uni2", "3- uni3" }));

        label3.setText("Author");

        Journal_Author.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Author1", "2- Author2", "3 Author3" }));

        label4.setText("Publisher");

        Journal_Publisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Pub1", "2- Pub2", "3- Pub3" }));

        label5.setText("Year");

        Journal_Year.addActionListener(this::Journal_YearActionPerformed);

        label6.setText("City");

        Journal_City.addActionListener(this::Journal_CityActionPerformed);

        label7.setText("Index");

        Journal_Index.setForeground(new java.awt.Color(204, 204, 204));
        Journal_Index.setText("Scopus 2, Sinta 1, ...");
        Journal_Index.addActionListener(this::Journal_IndexActionPerformed);

        Journal_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Institute", "Author", "Publisher", "Year", "City", "Index", "Status"
            }
        ));
        Journal_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Journal_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Journal_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Journal_Table);

        Add_Journal.setText("Add");

        Edit_Journal.setText("Edit");

        Refresh_Journal.setText("Refresh");

        Delete_Journal.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Journal.setText("Delete");

        javax.swing.GroupLayout JournalLayout = new javax.swing.GroupLayout(Journal);
        Journal.setLayout(JournalLayout);
        JournalLayout.setHorizontalGroup(
            JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JournalLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Journal_Institute, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Journal_Title)
                            .addComponent(Journal_Author, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Journal_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addComponent(Add_Journal)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_Journal)))
                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(Refresh_Journal)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_Journal))
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JournalLayout.createSequentialGroup()
                                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Journal_Year, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                    .addComponent(Journal_City)))
                            .addGroup(JournalLayout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(Journal_Index, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JournalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        JournalLayout.setVerticalGroup(
            JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JournalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Journal_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Journal_Institute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JournalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Journal_Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JournalLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JournalLayout.createSequentialGroup()
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Journal_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Journal_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Journal_Index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Journal_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(JournalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Journal)
                    .addComponent(Edit_Journal)
                    .addComponent(Refresh_Journal)
                    .addComponent(Delete_Journal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        TabMenu.addTab("Journal", Journal);

        label8.setText("Name");

        Institute_Name.addActionListener(this::Institute_NameActionPerformed);

        label9.setText("Contact");

        label18.setText("City");

        Institute_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact", "City"
            }
        ));
        Institute_Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Institute_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Institute_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Institute_Table);

        Add_Institute.setText("Add");

        Edit_Institute.setText("Edit");

        Refresh_Institute.setText("Refresh");

        Delete_Institute.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Institute.setText("Delete");

        javax.swing.GroupLayout InstituteLayout = new javax.swing.GroupLayout(Institute);
        Institute.setLayout(InstituteLayout);
        InstituteLayout.setHorizontalGroup(
            InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstituteLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Add_Institute)
                .addGap(42, 42, 42)
                .addComponent(Edit_Institute)
                .addGap(49, 49, 49)
                .addComponent(Refresh_Institute)
                .addGap(42, 42, 42)
                .addComponent(Delete_Institute)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(InstituteLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Institute_City)
                    .addComponent(Institute_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(Institute_Contact))
                .addGap(296, 296, 296))
            .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InstituteLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        InstituteLayout.setVerticalGroup(
            InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstituteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Institute_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Institute_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Institute_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Institute)
                    .addComponent(Edit_Institute)
                    .addComponent(Refresh_Institute)
                    .addComponent(Delete_Institute))
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(InstituteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InstituteLayout.createSequentialGroup()
                    .addGap(253, 253, 253)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        TabMenu.addTab("Institute", Institute);

        label10.setText("Name");

        label11.setText("Contact");

        Auth_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact"
            }
        ));
        jScrollPane4.setViewportView(Auth_Table);

        Add_Auth.setText("Add");

        Edit_Auth.setText("Edit");

        Refresh_Auth.setText("Refresh");

        Delete_Auth.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Auth.setText("Delete");

        javax.swing.GroupLayout AuthorLayout = new javax.swing.GroupLayout(Author);
        Author.setLayout(AuthorLayout);
        AuthorLayout.setHorizontalGroup(
            AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorLayout.createSequentialGroup()
                .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AuthorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Auth_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Auth_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AuthorLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Add_Auth)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_Auth)
                        .addGap(47, 47, 47)
                        .addComponent(Refresh_Auth)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_Auth))
                    .addGroup(AuthorLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        AuthorLayout.setVerticalGroup(
            AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuthorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Auth_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Auth_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Auth)
                    .addComponent(Edit_Auth)
                    .addComponent(Refresh_Auth)
                    .addComponent(Delete_Auth))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TabMenu.addTab("Author", Author);

        label12.setText("Name");

        label13.setText("Contact");

        Pub_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact"
            }
        ));
        jScrollPane5.setViewportView(Pub_Table);

        Add_Pub.setText("Add");

        Edit_Pub.setText("Edit");

        Refresh_Pub.setText("Refresh");

        Delete_Pub.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Pub.setText("Delete");

        javax.swing.GroupLayout PublisherLayout = new javax.swing.GroupLayout(Publisher);
        Publisher.setLayout(PublisherLayout);
        PublisherLayout.setHorizontalGroup(
            PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublisherLayout.createSequentialGroup()
                .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PublisherLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pub_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pub_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PublisherLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Add_Pub)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_Pub)
                        .addGap(47, 47, 47)
                        .addComponent(Refresh_Pub)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_Pub))
                    .addGroup(PublisherLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PublisherLayout.setVerticalGroup(
            PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PublisherLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pub_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pub_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PublisherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Pub)
                    .addComponent(Edit_Pub)
                    .addComponent(Refresh_Pub)
                    .addComponent(Delete_Pub))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TabMenu.addTab("Publisher", Publisher);

        label14.setText("Journal ID");

        Borrow_Journal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Journal1", "2- Journal2", "3- Journal3" }));

        label15.setText("Member ID");

        Borrow_Member.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Member1", "2- Member2", "3- Member3" }));
        Borrow_Member.addItemListener(this::countDate);

        label16.setText("Borrow");

        Borrow_Date.setText("dd/mm/yyyy");
        Borrow_Date.addActionListener(this::Borrow_DateActionPerformed);

        label17.setText("Return");

        Return_Date.setText("dd/mm/yyyy");
        Return_Date.addActionListener(this::Return_DateActionPerformed);

        Borrow_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Journal ID", "Member ID", "Borrow Date", "Return Date"
            }
        ));
        jScrollPane6.setViewportView(Borrow_Table);

        Add_Borrow.setText("Add");

        Edit_Borrow.setText("Edit");

        Refresh_Borrow.setText("Refresh");

        Delete_Borrow.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Borrow.setText("Delete");

        javax.swing.GroupLayout BorrowLayout = new javax.swing.GroupLayout(Borrow);
        Borrow.setLayout(BorrowLayout);
        BorrowLayout.setHorizontalGroup(
            BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowLayout.createSequentialGroup()
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BorrowLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Borrow_Member, 0, 120, Short.MAX_VALUE)
                            .addComponent(Borrow_Journal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Borrow_Date)
                            .addComponent(Return_Date)))
                    .addGroup(BorrowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BorrowLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(Add_Borrow)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_Borrow)
                        .addGap(47, 47, 47)
                        .addComponent(Refresh_Borrow)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_Borrow)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        BorrowLayout.setVerticalGroup(
            BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Borrow_Journal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Borrow_Member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Borrow_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Return_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Borrow)
                    .addComponent(Edit_Borrow)
                    .addComponent(Refresh_Borrow)
                    .addComponent(Delete_Borrow))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        TabMenu.addTab("Issued Journal", Borrow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TabMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Journal_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Journal_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Journal_TitleActionPerformed

    private void Journal_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Journal_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Journal_YearActionPerformed

    private void Journal_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Journal_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Journal_CityActionPerformed

    private void Journal_IndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Journal_IndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Journal_IndexActionPerformed

    private void Journal_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Journal_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Journal_TableMouseClicked

    private void Institute_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Institute_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Institute_NameActionPerformed

    private void Institute_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Institute_TableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Institute_TableMouseClicked

    private void Borrow_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrow_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Borrow_DateActionPerformed

    private void Return_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Return_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Return_DateActionPerformed

    private void countDate(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_countDate
        // TODO add your handling code here:
    }//GEN-LAST:event_countDate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Page_Journal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Auth;
    private javax.swing.JButton Add_Borrow;
    private javax.swing.JButton Add_Institute;
    private javax.swing.JButton Add_Journal;
    private javax.swing.JButton Add_Pub;
    private javax.swing.JTextField Auth_Contact;
    private javax.swing.JTextField Auth_Name;
    private javax.swing.JTable Auth_Table;
    private javax.swing.JPanel Author;
    private javax.swing.JPanel Borrow;
    private javax.swing.JTextField Borrow_Date;
    private javax.swing.JComboBox<String> Borrow_Journal;
    private javax.swing.JComboBox<String> Borrow_Member;
    private javax.swing.JTable Borrow_Table;
    private javax.swing.JButton Delete_Auth;
    private javax.swing.JButton Delete_Borrow;
    private javax.swing.JButton Delete_Institute;
    private javax.swing.JButton Delete_Journal;
    private javax.swing.JButton Delete_Pub;
    private javax.swing.JButton Edit_Auth;
    private javax.swing.JButton Edit_Borrow;
    private javax.swing.JButton Edit_Institute;
    private javax.swing.JButton Edit_Journal;
    private javax.swing.JButton Edit_Pub;
    private javax.swing.JPanel Institute;
    private javax.swing.JTextField Institute_City;
    private javax.swing.JTextField Institute_Contact;
    private javax.swing.JTextField Institute_Name;
    private javax.swing.JTable Institute_Table;
    private javax.swing.JPanel Journal;
    private javax.swing.JComboBox<String> Journal_Author;
    private javax.swing.JTextField Journal_City;
    private javax.swing.JTextField Journal_Index;
    private javax.swing.JComboBox<String> Journal_Institute;
    private javax.swing.JComboBox<String> Journal_Publisher;
    private javax.swing.JTable Journal_Table;
    private javax.swing.JTextField Journal_Title;
    private javax.swing.JTextField Journal_Year;
    private java.awt.Button LogOutButton;
    private java.awt.Button MenuButton;
    private javax.swing.JTextField Pub_Contact;
    private javax.swing.JTextField Pub_Name;
    private javax.swing.JTable Pub_Table;
    private javax.swing.JPanel Publisher;
    private javax.swing.JButton Refresh_Auth;
    private javax.swing.JButton Refresh_Borrow;
    private javax.swing.JButton Refresh_Institute;
    private javax.swing.JButton Refresh_Journal;
    private javax.swing.JButton Refresh_Pub;
    private javax.swing.JTextField Return_Date;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
