/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project.oovp2026;
import java.text.SimpleDateFormat;
import java.util.Calendar;
public class Page_Member extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Page_Member.class.getName());

    /**
     * Creates new form Page_Book
     */
    public Page_Member() {
        initComponents();
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat calFormat = new SimpleDateFormat("dd/MM/yyyy");
        Borrow_Date.setText(calFormat.format(cal.getTime()));
    }
    
    private void countDate() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();

            // Get the date from jTextField1
            cal.setTime(sdf.parse(Borrow_Date.getText()));

            // Logic duration from Borrow_Member (JComboBox)
            String selectedMember = Borrow_Member.getSelectedItem().toString();
            int duration = 7; // Default
            
            if (selectedMember.contains("Lect") || selectedMember.contains("Std") || selectedMember.contains("Gst")) {
                duration = 14;
            }

            cal.add(Calendar.DAY_OF_MONTH, duration);

            String returnDate = sdf.format(cal.getTime());
            label17.setText("Return Date: " + returnDate);

        } catch (Exception e) {
            System.err.println("Error while counting days: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutButton = new java.awt.Button();
        MenuButton = new java.awt.Button();
        TabMenu = new javax.swing.JTabbedPane();
        Member = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        Mem_Name = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        Mem_Reg_Date = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        Mem_Member_Type = new javax.swing.JComboBox<>();
        label2 = new java.awt.Label();
        Mem_Identifier = new javax.swing.JComboBox<>();
        label3 = new java.awt.Label();
        Mem_Email = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        Mem_Phone = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Mem_Table = new javax.swing.JTable();
        Add_Mem = new javax.swing.JButton();
        Edit_Mem = new javax.swing.JButton();
        Refresh_Mem = new javax.swing.JButton();
        Delete_Mem = new javax.swing.JButton();
        Member_Type = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        MT_Name = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        MT_Loan_Day = new javax.swing.JComboBox<>();
        label7 = new java.awt.Label();
        MT_Loan_Limit = new javax.swing.JComboBox<>();
        label8 = new java.awt.Label();
        MT_Fine = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        MT_Table = new javax.swing.JTable();
        Add_MT = new javax.swing.JButton();
        Edit_MT = new javax.swing.JButton();
        Refresh_MT = new javax.swing.JButton();
        Delete_MT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogOutButton.setLabel("Log Out");

        MenuButton.setLabel("Back to Menu");

        TabMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label10.setText("Name");

        label11.setText("Reg Date");

        Mem_Reg_Date.setForeground(new java.awt.Color(204, 204, 204));
        Mem_Reg_Date.setText("dd/mm/yyyy");

        label1.setText("Member Type");

        Mem_Member_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-Student", "2-Lecturer", "3-Guest" }));

        label2.setText("Identifier");

        Mem_Identifier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STD", "LEC", "GST" }));

        label3.setText("Email");

        Mem_Email.setForeground(new java.awt.Color(204, 204, 204));
        Mem_Email.setText("miaw@gmail.com");

        label4.setText("Phone Number");

        Mem_Phone.setForeground(new java.awt.Color(204, 204, 204));
        Mem_Phone.setText("0811-1234-5678");

        Mem_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Reg Date", "Member Type", "Identifier", "Email", "Phone Number"
            }
        ));
        jScrollPane4.setViewportView(Mem_Table);

        Add_Mem.setText("Add");
        Add_Mem.addActionListener(this::Add_MemActionPerformed);

        Edit_Mem.setText("Edit");

        Refresh_Mem.setText("Refresh");

        Delete_Mem.setForeground(new java.awt.Color(204, 0, 51));
        Delete_Mem.setText("Delete");

        javax.swing.GroupLayout MemberLayout = new javax.swing.GroupLayout(Member);
        Member.setLayout(MemberLayout);
        MemberLayout.setHorizontalGroup(
            MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLayout.createSequentialGroup()
                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Mem_Reg_Date, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(Mem_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(Mem_Member_Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MemberLayout.createSequentialGroup()
                                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Mem_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(Mem_Phone)
                                    .addComponent(Mem_Identifier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Add_Mem)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_Mem)
                        .addGap(47, 47, 47)
                        .addComponent(Refresh_Mem)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_Mem)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MemberLayout.setVerticalGroup(
            MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mem_Reg_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addComponent(Mem_Identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Mem_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Mem_Member_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Mem_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(MemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Mem)
                    .addComponent(Edit_Mem)
                    .addComponent(Refresh_Mem)
                    .addComponent(Delete_Mem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        TabMenu.addTab("Member", Member);

        label5.setText("Name");

        label6.setText("Loan Days");

        MT_Loan_Day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7 Days", "14 Days" }));

        label7.setText("Loan Limit");

        MT_Loan_Limit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 Books", "5 Books", "10 Books" }));
        MT_Loan_Limit.setToolTipText("");

        label8.setText("Fine per Day");

        MT_Fine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.25%", "0.50%", "1.00%" }));
        MT_Fine.setToolTipText("");

        MT_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Loan Days", "Loan Limit", "Fine per Day"
            }
        ));
        jScrollPane5.setViewportView(MT_Table);

        Add_MT.setText("Add");

        Edit_MT.setText("Edit");

        Refresh_MT.setText("Refresh");

        Delete_MT.setForeground(new java.awt.Color(204, 0, 51));
        Delete_MT.setText("Delete");

        javax.swing.GroupLayout Member_TypeLayout = new javax.swing.GroupLayout(Member_Type);
        Member_Type.setLayout(Member_TypeLayout);
        Member_TypeLayout.setHorizontalGroup(
            Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Member_TypeLayout.createSequentialGroup()
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Member_TypeLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Member_TypeLayout.createSequentialGroup()
                                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MT_Name)
                                    .addComponent(MT_Loan_Day, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MT_Loan_Limit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MT_Fine, 0, 120, Short.MAX_VALUE)))))
                    .addGroup(Member_TypeLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Member_TypeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Add_MT)
                        .addGap(42, 42, 42)
                        .addComponent(Edit_MT)
                        .addGap(47, 47, 47)
                        .addComponent(Refresh_MT)
                        .addGap(42, 42, 42)
                        .addComponent(Delete_MT)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Member_TypeLayout.setVerticalGroup(
            Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Member_TypeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MT_Loan_Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MT_Loan_Limit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MT_Fine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Member_TypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_MT)
                    .addComponent(Edit_MT)
                    .addComponent(Refresh_MT)
                    .addComponent(Delete_MT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TabMenu.addTab("Member Type", Member_Type);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TabMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_MemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_MemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Page_Member().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_MT;
    private javax.swing.JButton Add_Mem;
    private javax.swing.JButton Delete_MT;
    private javax.swing.JButton Delete_Mem;
    private javax.swing.JButton Edit_MT;
    private javax.swing.JButton Edit_Mem;
    private java.awt.Button LogOutButton;
    private javax.swing.JComboBox<String> MT_Fine;
    private javax.swing.JComboBox<String> MT_Loan_Day;
    private javax.swing.JComboBox<String> MT_Loan_Limit;
    private javax.swing.JTextField MT_Name;
    private javax.swing.JTable MT_Table;
    private javax.swing.JTextField Mem_Email;
    private javax.swing.JComboBox<String> Mem_Identifier;
    private javax.swing.JComboBox<String> Mem_Member_Type;
    private javax.swing.JTextField Mem_Name;
    private javax.swing.JTextField Mem_Phone;
    private javax.swing.JTextField Mem_Reg_Date;
    private javax.swing.JTable Mem_Table;
    private javax.swing.JPanel Member;
    private javax.swing.JPanel Member_Type;
    private java.awt.Button MenuButton;
    private javax.swing.JButton Refresh_MT;
    private javax.swing.JButton Refresh_Mem;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables
}
